### ISSUE TITLE
PQnotifies definition

### ISSUE THREAD

**Issue by IMNdi** [stijnsanders/DataLank#1]
I wanted to do a pull request then I realized I don't know anything about pull requests. So an issue it is.

`function PQnotifies(conn: PGconn): PGnotify; cdecl;`

This is incorrect. Function PQnotifies returns null if there are no notifications, this creates an error (Access Violation) in the host app. The definition should be 

`function PQnotifies(conn: PGconn): PPGnotify; cdecl;`

It should return a pointer. That way,
```
PN := PQnotifies(conn);
 if PN = nil then Exit else ShowMessage (PN.Extra);
```
^ this works.
-------------

Another half-issue is the definition of PGNotify
It has a member called Next. I think I see why it's there, because libpq-fe.h has it. However, I can find no documentation on PostgreSQL's website about a .Next. I looked in old and new docs and there's no reference to it. 

Additionally, there is a comment that 
`/* Fields below here are private to libpq; apps should not use 'em */`
in https://github.com/postgres/postgres/blob/master/src/interfaces/libpq/libpq-fe.h

Since this is meant to be an interface to develop on the app end, should that be there? Also, the mechanism that makes Notifies tick (PQconsumeInput) specifically claims to pull only the next message in queue. Next is unlikely to be used any time soon.

**Comment by stijnsanders** [comment]
An issue is fine. A pull request is nice, but takes more work. You can read about it [on the net if you look around.](https://duckduckgo.com/?q=github+pull+request+howto&atb=v314-1&ia=web)
I've updated the PQnotifies signature (looking at it now, it looks like this may have been a typing error, and I wrote a P too few in 'PpgNitofy'), and dropped the 'next' member. I haven't gotten around to using listen/notify myself so I can't test rightaway, but what you describe makes sense, so I accept that you made it work as confirmation.
Also I need to make some time sometime soon and check if there's anything new in newer PostgreSQL versions since I've done this.
